/* eslint-disable max-classes-per-file */
/** Declaration file generated by dts-gen */
declare module 'pagedjs' {
  export class Chunker {
    constructor(content: any, renderTo: any, options: any);
    addPage(blank: any): any;
    clonePage(_x8: any, ...args: any[]): any;
    destroy(): void;
    emit(type: any, ...args: any[]): void;
    flow(_x: any, _x2: any, ...args: any[]): any;
    handleBreaks(_x6: any, _x7: any, ...args: any[]): any;
    layout(content: any, startAt: any): any;
    loadFonts(): any;
    off(type: any, listener: any): any;
    on(type: any, listener: any): any;
    once(type: any, listener: any, ...args: any[]): any;
    recoredCharLength(length: any): void;
    removePages(...args: any[]): void;
    render(_x3: any, _x4: any, ...args: any[]): any;
    renderAsync(_x5: any, ...args: any[]): any;
    renderOnIdle(renderer: any): any;
    setup(renderTo: any): void;
    start(): void;
    stop(): void;
  }

  export class Handler {
    constructor(chunker: any, polisher: any, caller: any);
    emit(type: any, ...args: any[]): void;
    off(type: any, listener: any): any;
    on(type: any, listener: any): any;
    once(type: any, listener: any, ...args: any[]): any;
  }

  export class Polisher {
    constructor(setup: any);
    add(...args: any[]): any;
    convertViaSheet(_x2: any, _x3: any, ...args: any[]): any;
    destroy(): void;
    insert(text: any): any;
    setup(): any;
  }

  export class Previewer {
    constructor(options?: any);
    emit(type: any, ...args: any[]): void;
    getParams(name: any): any;
    initializeHandlers(): any;
    off(type: any, listener: any): any;
    on(type: any, listener: any): any;
    once(type: any, listener: any, ...args: any[]): any;
    preview(_x: any, _x2: any, _x3: any, ...args: any[]): any;
    registerHandlers(...args: any[]): any;
    removeStyles(...args: any[]): any;
    wrapContent(): any;
  }

  export const registeredHandlers: any[];

  export function initializeHandlers(
    chunker: any,
    polisher: any,
    caller: any,
  ): any;

  export function registerHandlers(...args: any[]): void;
}
